.gitignore
QuadradiusR/prefabs/buttons/learn_the_game.tscn
QuadradiusR/scripts/buttons/learn_the_game.gd

add learn the game button

---

QuadradiusR/prefabs/buttons/generic_button.tscn
QuadradiusR/prefabs/buttons/remember_pw.tscn
QuadradiusR/prefabs/buttons/start.tscn
QuadradiusR/scripts/toggle_button.gd

add remember pw button

---

QuadradiusR/resources/fonts/115_OCR A Extended_11pt_st.tres
QuadradiusR/resources/fonts/12_Fette Engschrift.tres
QuadradiusR/resources/fonts/64_Fette Engschrift.tres
QuadradiusR/resources/fonts/72_DotMatrix.tres
QuadradiusR/resources/fonts/75_OCR A Extended.tres

add font resources

---

.gitignore
QuadradiusR/scripts/generic_button.gd
QuadradiusR/scripts/toggle_button.gd

Fixed small variable usage problem

Fix animator variable usage

---

QuadradiusR/prefabs/buttons/start.tscn
QuadradiusR/prefabs/login_input_ui.tscn
QuadradiusR/resources/fonts/72_DotMatrix.tres
QuadradiusR/scripts/login_input_ui.gd
QuadradiusR/scripts/toggle_button.gd

Feature/46 login input UI

---

QuadradiusR/prefabs/network_handler.tscn
QuadradiusR/project.godot
QuadradiusR/scripts/message_template.gd
QuadradiusR/scripts/network_handler.gd

add network handler node

---

QuadradiusR/scripts/network_handler.gd

[#54] add const and preload

---

QuadradiusR/resources/fonts/75_OCR A Extended.tres
QuadradiusR/scenes/lobby.tscn
QuadradiusR/scripts/lobby_manager.gd
QuadradiusR/scripts/player_list.gd
QuadradiusR/scripts/player_list_row.gd

Closes #76 
Lobby static ui needs replacing with assets and deleting pre-rendered static elements like text and buttons.
The sound after challenging player does not start because the scene switches over too quickly.

add lobby draft

---

QuadradiusR/scenes/game.tscn

add game scene draft

---

QuadradiusR/prefabs/buttons/start_game_button.tscn

add start game button

---

QuadradiusR/prefabs/torus.tscn
QuadradiusR/scenes/game.tscn
QuadradiusR/scripts/torus.gd

torus static

---

QuadradiusR/prefabs/buttons/play_again_button.tscn

add play again button

---

QuadradiusR/prefabs/board.tscn
QuadradiusR/prefabs/tile.tscn
QuadradiusR/prefabs/torus.tscn
QuadradiusR/scripts/board.gd
QuadradiusR/scripts/tile.gd
QuadradiusR/scripts/torus.gd

Board with drag and drop

---

QuadradiusR/prefabs/tile.tscn
QuadradiusR/prefabs/torus.tscn
QuadradiusR/project.godot
QuadradiusR/scripts/board.gd
QuadradiusR/scripts/movement_powerup_manager.gd
QuadradiusR/scripts/powerups/abstract.gd
QuadradiusR/scripts/powerups/torus_base.gd
QuadradiusR/scripts/tile.gd
QuadradiusR/scripts/torus.gd

improved drag and drop draft

---

QuadradiusR/prefabs/board.tscn
QuadradiusR/prefabs/tile.tscn
QuadradiusR/prefabs/torus.tscn
QuadradiusR/project.godot
QuadradiusR/scripts/board.gd
QuadradiusR/scripts/tile.gd
QuadradiusR/scripts/torus.gd

Destroying toruses

---

QuadradiusR/scenes/game.tscn
QuadradiusR/scripts/board.gd

setup test game scene

---

QuadradiusR/prefabs/tile.tscn
QuadradiusR/scenes/game.tscn
QuadradiusR/scripts/tile.gd

add randomised scuff marks

---

QuadradiusR/prefabs/tile.tscn
QuadradiusR/scripts/tile.gd

There is a bug related to putting down a torus on a tile after I added elevation (#127).
closes #122

[#122] Add tile elevation without SFX

---

QuadradiusR/scripts/board.gd

update tile resolution method

---

Server/src/quadradiusr_server/cli.py
Server/src/quadradiusr_server/config.py

Server: add config generator

---

Server/src/quadradiusr_server/cli.py
Server/src/quadradiusr_server/cron.py
Server/src/quadradiusr_server/rest/user_views.py
Server/src/quadradiusr_server/server.py

Server: add logging and handle KeyboardInterrupt

---

QuadradiusR/scripts/board.gd
QuadradiusR/scripts/torus.gd

refactor torus to use tile reference

---

Documentation/source/api/02_rest_api.rst
Server/src/quadradiusr_server/lobby.py
Server/src/quadradiusr_server/rest/game_invite_views.py
Server/src/quadradiusr_server/rest/game_views.py
Server/src/quadradiusr_server/rest/lobby_views.py
Server/tests/e2e/test_e2e_game_invite_notification.py
Server/tests/rest/test_game_invite.py
Server/tests/rest/test_lobby.py
Server/tests/ws/test_ws_lobby.py

Server: add player list to lobby

---

QuadradiusR/prefabs/buttons/generic_black_button.tscn

add generic black button

---

QuadradiusR/prefabs/tile.tscn
QuadradiusR/scripts/board.gd
QuadradiusR/scripts/tile.gd
QuadradiusR/scripts/torus.gd

Add highlight

---

QuadradiusR/prefabs/network_handler.tscn
QuadradiusR/prefabs/player_list.tscn
QuadradiusR/project.godot
QuadradiusR/scripts/lobby_manager.gd
QuadradiusR/scripts/login_manager.gd
QuadradiusR/scripts/message_template.gd
QuadradiusR/scripts/network_handler.gd
QuadradiusR/scripts/rest_api.gd
QuadradiusR/scripts/ws_api.gd

add lobby player list loading

---

QuadradiusR/scenes/game.tscn

Add right panel base

---

Documentation/source/api/06_ws_notifications.rst
Server/src/quadradiusr_server/lobby.py
Server/src/quadradiusr_server/qrws_connection.py
Server/src/quadradiusr_server/server.py
Server/tests/e2e/test_e2e_lobby_join_notification.py

Server: add notifications for lobby players

---

Server/src/quadradiusr_server/db/base.py
Server/src/quadradiusr_server/db/repository.py
Server/src/quadradiusr_server/game.py
Server/src/quadradiusr_server/lobby.py
Server/src/quadradiusr_server/rest/game_views.py
Server/src/quadradiusr_server/rest/lobby_views.py
Server/src/quadradiusr_server/server.py
Server/tests/test_base.py
Server/tests/ws/test_ws_lobby.py

Server: fix #173, add clone_db_object

---

Documentation/source/api/02_rest_api.rst
Documentation/source/api/06_ws_notifications.rst
Server/src/quadradiusr_server/rest/game_invite_views.py
Server/src/quadradiusr_server/rest/game_views.py
Server/src/quadradiusr_server/rest/mappers.py

Server: send full objects in notifications

---

QuadradiusR/prefabs/login_input_ui.tscn
QuadradiusR/prefabs/player_list.tscn
QuadradiusR/resources/fonts/72_DotMatrix.tres
QuadradiusR/scenes/game.tscn
QuadradiusR/scenes/lobby.tscn
QuadradiusR/scripts/lobby_manager.gd
QuadradiusR/scripts/login_manager.gd
QuadradiusR/scripts/network_handler.gd
QuadradiusR/scripts/player_list.gd
QuadradiusR/scripts/player_list_row.gd
QuadradiusR/scripts/rest_api.gd
QuadradiusR/scripts/ws_api.gd

Closes #160 
Implement websocket topic subscriptons, notifications, signals
Add invitation system with acceptance, etc. For now redirects to game page

Lobby Invites

---

Documentation/source/api/02_rest_api.rst
Documentation/source/api/04_ws_messages.rst
Documentation/source/api/05_ws_message_flows.rst
Documentation/source/api/06_ws_notifications.rst
Server/src/quadradiusr_server/constants.py
Server/src/quadradiusr_server/lobby.py
Server/src/quadradiusr_server/qrws_messages.py
Server/src/quadradiusr_server/rest/lobby_views.py
Server/src/quadradiusr_server/rest/mappers.py
Server/src/quadradiusr_server/server.py
Server/tests/harness/__init__.py
Server/tests/ws/test_ws_lobby.py

Server: send messages as notifications

---

Documentation/source/api/02_rest_api.rst
Documentation/source/api/04_ws_messages.rst
Documentation/source/api/05_ws_message_flows.rst
Server/src/quadradiusr_server/constants.py
Server/src/quadradiusr_server/db/game_invite_repository.py
Server/src/quadradiusr_server/db/lobby_repository.py
Server/src/quadradiusr_server/game.py
Server/src/quadradiusr_server/lobby.py
Server/src/quadradiusr_server/qrws_connection.py
Server/src/quadradiusr_server/qrws_messages.py
Server/src/quadradiusr_server/rest/game_invite_views.py
Server/src/quadradiusr_server/rest/game_views.py
Server/src/quadradiusr_server/utils.py
Server/tests/e2e/test_e2e_basic_game.py
Server/tests/harness/__init__.py
Server/tests/rest/test_game.py

Server: implement moving pieces

---

.gitmodules

* revision is invalid
* GitHub disabled HTTP authorization

Fix original_assets submodule

---

.dockerignore
Dockerfile.bundle
Makefile
QuadradiusR/Makefile
Server/docker/entrypoint.sh
Server/src/quadradiusr_server/config.py
Server/src/quadradiusr_server/qrws_connection.py
Server/src/quadradiusr_server/server.py
Server/tests/test_static_files.py

Add Dockerfile for Godot HTML and Server bundle

---

Documentation/source/api/02_rest_api.rst
Server/src/quadradiusr_server/db/base.py
Server/src/quadradiusr_server/db/repository.py
Server/src/quadradiusr_server/db/transactions.py
Server/src/quadradiusr_server/game.py
Server/tests/e2e/test_e2e_basic_game.py
Server/tests/harness/__init__.py
Server/tests/rest/test_game.py
Server/tests/test_game.py
Server/tests/ws/test_ws_game.py

Server: implement & test player turns

---

Documentation/source/api/02_rest_api.rst
Server/src/quadradiusr_server/game.py
Server/tests/ws/test_ws_game.py

Server: handle victory

---

Server/src/quadradiusr_server/cron.py
Server/src/quadradiusr_server/notification.py
Server/src/quadradiusr_server/qrws_connection.py
Server/tests/e2e/test_e2e_lobby_join_notification.py
Server/tests/harness/__init__.py
Server/tests/test_cron.py

Server: fix duplicate notifications

---

QuadradiusR/scripts/player_list.gd

delete invite from cache when player leaves

---

QuadradiusR/scripts/login_manager.gd
QuadradiusR/scripts/player_list.gd

add auto registration for users

---

QuadradiusR/prefabs/context.tscn
QuadradiusR/prefabs/login_input_ui.tscn
QuadradiusR/prefabs/right_side_panel.tscn
QuadradiusR/prefabs/tile.tscn
QuadradiusR/project.godot
QuadradiusR/scenes/game.tscn
QuadradiusR/scenes/match_settings.tscn
QuadradiusR/scripts/board.gd
QuadradiusR/scripts/context.gd
QuadradiusR/scripts/game_manager.gd
QuadradiusR/scripts/game_state.gd
QuadradiusR/scripts/lobby_manager.gd
QuadradiusR/scripts/login_manager.gd
QuadradiusR/scripts/match_settings_manager.gd
QuadradiusR/scripts/message_template.gd
QuadradiusR/scripts/network_handler.gd
QuadradiusR/scripts/player_list.gd
QuadradiusR/scripts/rest_api.gd
QuadradiusR/scripts/tile.gd
QuadradiusR/scripts/torus.gd
QuadradiusR/scripts/ws_api.gd

Client: Implement turns

---

QuadradiusR/scenes/lobby.tscn
QuadradiusR/scenes/login.tscn
QuadradiusR/scripts/network_handler.gd

* Scale textures down
* Fix code for HTML5 quirks

Game: optimize lobby for HTML5

---

QuadradiusR/scripts/login_manager.gd

Client: fix infinite loop when passing wrong credentials

---

QuadradiusR/prefabs/torus.tscn

Client: fix positional audio in game

---

QuadradiusR/scripts/lobby_manager.gd
QuadradiusR/scripts/network_handler.gd
QuadradiusR/scripts/player_list.gd

Client: fix race condition in lobby player list

---

Documentation/source/game.rst
Documentation/source/game/network_handler.rst
Documentation/source/game/ws_api.rst
Documentation/source/index.rst

Add basic game documentation

---

QuadradiusR/prefabs/orb.tscn
QuadradiusR/prefabs/tile.tscn
QuadradiusR/scripts/tile.gd

add animated orb prefab

---

Server/src/quadradiusr_server/game.py
Server/tests/ws/test_ws_game.py

Server: broadcast game state only to connected players

---

QuadradiusR/prefabs/board.tscn
QuadradiusR/prefabs/right_side_panel.tscn
QuadradiusR/scenes/game.tscn
QuadradiusR/scripts/context.gd
QuadradiusR/scripts/game_manager.gd
QuadradiusR/scripts/network_handler.gd
QuadradiusR/scripts/right_side_panel.gd

Game: properly show usernames and turn

---

Server/src/quadradiusr_server/db/base.py
Server/src/quadradiusr_server/game.py
Server/src/quadradiusr_server/lobby.py
Server/src/quadradiusr_server/logger.py
Server/src/quadradiusr_server/rest/user_views.py

* Prevent duplicate logs by registering handlers only once
* Add logging

Server: improve logging

---

QuadradiusR/scenes/game.tscn
QuadradiusR/scripts/message_template.gd
QuadradiusR/scripts/network_handler.gd
QuadradiusR/scripts/rest_api.gd

Handling redirects, some errors occured on server while testing 
Closes #253

[#253] Handle redirects

---

QuadradiusR/prefabs/orb.tscn
QuadradiusR/prefabs/tile.tscn
QuadradiusR/prefabs/torus.tscn
QuadradiusR/scripts/board.gd
QuadradiusR/scripts/context.gd
QuadradiusR/scripts/game_manager.gd
QuadradiusR/scripts/game_state.gd
QuadradiusR/scripts/login_manager.gd
QuadradiusR/scripts/orb.gd
QuadradiusR/scripts/tile.gd
QuadradiusR/scripts/torus.gd

Client: Powerup

---

.github/workflows/python-ci.yml
Dockerfile.bundle
Server/.dockerignore
Server/build_scripts.py
Server/pyproject.toml
Server/requirements.ci.txt

Server: add support for PyInstaller

---

QuadradiusR/project.godot
QuadradiusR/scripts/embedded_server.gd
QuadradiusR/scripts/network_handler.gd
Server/src/quadradiusr_server/cli.py
Server/src/quadradiusr_server/config.py
Server/src/quadradiusr_server/server.py

Game: add support for embedded server

---

QuadradiusR/prefabs/full_power_list_row.tscn
QuadradiusR/prefabs/piece_power_list.tscn
QuadradiusR/prefabs/piece_power_list_row.tscn
QuadradiusR/prefabs/player_list_row.tscn
QuadradiusR/prefabs/power_list_row.tscn
QuadradiusR/prefabs/powerup_list.tscn
QuadradiusR/prefabs/torus.tscn
QuadradiusR/scripts/context.gd
QuadradiusR/scripts/embedded_server.gd
QuadradiusR/scripts/full_power_list.gd
QuadradiusR/scripts/full_power_list_row.gd
QuadradiusR/scripts/game_manager.gd
QuadradiusR/scripts/network_handler.gd
QuadradiusR/scripts/orb.gd
QuadradiusR/scripts/piece_power_list.gd
QuadradiusR/scripts/piece_power_list_row.gd
QuadradiusR/scripts/power_list_row.gd
QuadradiusR/scripts/powerup_list.gd
QuadradiusR/scripts/rest_api.gd
QuadradiusR/scripts/right_side_panel.gd
QuadradiusR/scripts/torus.gd
QuadradiusR/scripts/ws_api.gd

Client: Apply powerups
